package com.oustme.oustsdk.activity.courses.newlearnngmap;

import com.google.firebase.database.DataSnapshot;
import com.oustme.oustsdk.commonmvp.mvp.view.BaseView;
import com.oustme.oustsdk.firebase.course.CourseDataClass;
import com.oustme.oustsdk.firebase.course.CourseLevelClass;
import com.oustme.oustsdk.firebase.course.SearchCourseLevel;
import com.oustme.oustsdk.response.common.Popup;
import com.oustme.oustsdk.response.course.CommonResponse;
import com.oustme.oustsdk.room.dto.DTOUserCourseData;

import java.util.List;
import java.util.Map;

public interface LearningMapView extends BaseView {
    void setFontAndText();
    void setLanguage(String language);
    void setDownloadCourseIcon(DTOUserCourseData userCourseData);
    void setReviewModeStatus(boolean isReviewMode);
    void setReviewMode(boolean reviewMode);
    void showLeaderBoard();
    void showBulletinBoard();
    void showCourseReviewLayout();
    void updateReviewList();
    void setText();
    void startCourseDownload();
    void setCurrentModuleCompleteLevel(int percentage);
    void setLpOcText(long mytotalOc, long totalOc);
    void endActivity();
    void gotoLeaderBoard(int currentLearningPathId, String lpName, String bgimg);
    void gotoBulletinBoard(int currentLearningPathId, String lpName);
    void sendUnlockPathApi(int currentLearningPathId);
    void downloadCourse(CourseDataClass courseDataClass);
    void showPopup(Popup popup);
    void hideLoader();
    void showRetry();
    void updateLevelDownloadStatus(int noofLevels, final CourseDataClass courseDataClass, DTOUserCourseData dtoUserCourseData);
    void setBackLayer(String imagePath);
    void setAllLevelList(List<SearchCourseLevel> levelList);
    void createLevelList(List<SearchCourseLevel> levelList, boolean allCourseSearchMode);
    void setCertificateVisibility(DTOUserCourseData userCourseData, final CourseDataClass courseDataClass);
    void setLpName(String lpName);
    void addLevelIcons(int scrWidth, int scrHeight, int scrollviewHeight, int noofLevels, int maxloackedLevel, CourseDataClass courseDataClass, DTOUserCourseData dtoUserCourseData);
    void addLevelDescription(int scrWidth, int scrHeight, int scrollviewHeight, int noofLevels, int lastlevelno, int currentlevleno, final CourseDataClass courseDataClass, DTOUserCourseData dtoUserCourseData);
    void setIndicatorPosition(int lastPlayingLevel, int currentlevleno, int scrWidth, int scrHeight, int scrollViewHeight, DTOUserCourseData dtoUserCourseData, CourseDataClass courseDataClass);
    void startLearningPath();
    void checkMultiLingualCourse();
    void setBackLine(int scrWidth, int scrHeight, int scrollViewHeight, int nooflevels);
    void bringBackFront();
    void setLearningStartIcon(int scrWidth, int scrHeight, int scrollviewHeight);
    void addOverLay(int scrWidth, int scrHeight, int scrollviewHeight);
    void setLearningStartLabbelIcon(int scrWidth, int scrHeight, int scrollviewHeight);
    void setCurrentLevelPosition(int currentLevel, int scrHeight, int scrollViewHeight);
    void onScrollPostMeth();
    void enableClick();
    void gotoQuizPage(int currentLearningPathId, CourseDataClass courseDataClass, int levelNo, CourseLevelClass courseLevelClass);
    void setLevelChangeAnim(final int currentLevel, final int scrWidth, final int scrHeight, final int scrollViewHeight, final int totalNoofLevels, final CourseDataClass courseDataClass);
    void gotoQuizPageReviewMode(int currentLearningPathId, CourseDataClass courseDataClass, int levelNo, int reviewModeQuestionNo);
    void gotoAssessmentPage(int currentLearningPathId, CourseDataClass courseDataClass);
    void startDownloadLevel(CourseLevelClass courseLevelClass, String courseUniqNoStr);
    void extractCourseData(final int learningPathId, Map<String, Object> learingMap, Map<String, Object> landingMap);
    void setBulletinQuesFromFirebase(DataSnapshot dataSnapshot);
    void updateUserData(final int lpId, final CourseDataClass courseDataClass, Map<String, Object> learingMap);
    void showstored_Popup();
    void hideCertificateLoader();
    void gotCertificateToMailResponse(String mail, CourseDataClass courseDataClass, CommonResponse commonResponse, boolean isComingFormCourseCompletePopup);
    void showCoins();
    void gotoRegularModeActivity(int learninPathId);
    void setLearningCardOpen(boolean isLearningCardOpen);
    void gotoSurveyPage();
}
